name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip backend project
      working-directory: ./backend
      run: zip -r app.zip . -x '*.git*' '.vscode/*' 'node_modules/*' 'dist/*' 'test/*' '*.github/*' '*.env'

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_GH_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_GH_SECRET_ACCESS_KEY }}
        application_name: Notespot
        environment_name: Notespot-env
        region: us-east-2
        version_label: ${{ github.sha }}
        deployment_package: backend/app.zip