name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Build and Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        # need to source nvm (to load npm and node) since these commands run in a non-interactive shell
        script: |
          cd /home/ubuntu/notespot/backend
          source ~/.nvm/nvm.sh
          nvm use node
          git pull origin main
          npm ci
          npm run build
          pm2 restart notespot || pm2 start dist/index.js --name notespot --env production