name: Deploy Backend to AWS Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_GH_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_GH_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to AWS Lambda
      working-directory: ./backend
      run: npm run deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
        CLOUDWATCH_ENABLED: ${{ vars.CLOUDWATCH_ENABLED }}